
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 34.201.45.32
    path: "/share"
